image: docker:git
services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com


build_daemon:
  script:
    - docker build -t registry.gitlab.com/gbraad/libvirt:daemon ./daemon/ 
    - docker push registry.gitlab.com/gbraad/libvirt:daemon
  only:
    - master

build_client:
  script:
    - docker build -t registry.gitlab.com/gbraad/libvirt:client ./client/ 
    - docker push registry.gitlab.com/gbraad/libvirt:client
  only:
    - master
